SELECT * FROM all_views WHERE view_name = 'FA_ADDITIONS_V';

SELECT AD.ROWID ROW_ID ,
  AD.ASSET_ID ,
  AD.ASSET_NUMBER ,
  AD.ASSET_KEY_CCID ,
  AD.CURRENT_UNITS ,
  AD.ASSET_TYPE ,
  AD.TAG_NUMBER ,
  ADT.DESCRIPTION ,
  AD.ASSET_CATEGORY_ID ,
  AD.PARENT_ASSET_ID ,
  AD.MANUFACTURER_NAME ,
  AD.SERIAL_NUMBER ,
  AD.MODEL_NUMBER ,
  AD.PROPERTY_TYPE_CODE ,
  lutl_pt.meaning PROPERTY_TYPE_MEANING,
  AD.PROPERTY_1245_1250_CODE,
  lutl_pc.meaning PROPERTY_1245_1250_MEANING,
  AD.IN_USE_FLAG ,
  AD.OWNED_LEASED ,
  AD.NEW_USED ,
  AD.UNIT_ADJUSTMENT_FLAG ,
  AD.ADD_COST_JE_FLAG ,
  AD.INVENTORIAL ,
  AD.ATTRIBUTE1 ,  AD.ATTRIBUTE2 ,  AD.ATTRIBUTE3 ,  AD.ATTRIBUTE4 ,  AD.ATTRIBUTE5 ,
  AD.ATTRIBUTE6 ,  AD.ATTRIBUTE7 ,  AD.ATTRIBUTE8 ,  AD.ATTRIBUTE9 ,  AD.ATTRIBUTE10 ,
  AD.ATTRIBUTE11 ,  AD.ATTRIBUTE12 ,  AD.ATTRIBUTE13 ,  AD.ATTRIBUTE14 ,  AD.ATTRIBUTE15 ,
  AD.ATTRIBUTE16 ,  AD.ATTRIBUTE17 ,  AD.ATTRIBUTE18 ,  AD.ATTRIBUTE19 ,  AD.ATTRIBUTE20 ,
  AD.ATTRIBUTE21 ,  AD.ATTRIBUTE22 ,  AD.ATTRIBUTE23 ,  AD.ATTRIBUTE24 ,  AD.ATTRIBUTE25 ,
  AD.ATTRIBUTE26 ,  AD.ATTRIBUTE27 ,  AD.ATTRIBUTE28 ,  AD.ATTRIBUTE29 ,  AD.ATTRIBUTE30 ,
  AD.ATTRIBUTE_CATEGORY_CODE ,
  AD.CONTEXT ,
  AD.LEASE_ID ,
  AD.LAST_UPDATE_DATE ,
  AD.LAST_UPDATED_BY ,
  AD.CREATED_BY ,
  AD.CREATION_DATE ,
  AD.LAST_UPDATE_LOGIN ,
  PAD.ASSET_NUMBER PARENT_ASSET ,
  PADT.DESCRIPTION PARENT_DESCRIPTION ,
  PV.VENDOR_NAME LESSOR ,
  LEASE.LEASE_NUMBER ,
  LEASE.DESCRIPTION LEASE_DESC ,
  LEASE.LESSOR_ID ,
  LEASE.ATTRIBUTE1 LS_ATTRIBUTE1 ,  LEASE.ATTRIBUTE2 LS_ATTRIBUTE2 ,  LEASE.ATTRIBUTE3 LS_ATTRIBUTE3 ,
  LEASE.ATTRIBUTE4 LS_ATTRIBUTE4 ,  LEASE.ATTRIBUTE5 LS_ATTRIBUTE5 ,  LEASE.ATTRIBUTE6 LS_ATTRIBUTE6 ,
  LEASE.ATTRIBUTE7 LS_ATTRIBUTE7 ,  LEASE.ATTRIBUTE8 LS_ATTRIBUTE8 ,  LEASE.ATTRIBUTE9 LS_ATTRIBUTE9 ,
  LEASE.ATTRIBUTE10 LS_ATTRIBUTE10 ,  LEASE.ATTRIBUTE11 LS_ATTRIBUTE11 ,  LEASE.ATTRIBUTE12 LS_ATTRIBUTE12 ,
  LEASE.ATTRIBUTE13 LS_ATTRIBUTE13 ,  LEASE.ATTRIBUTE14 LS_ATTRIBUTE14 ,  LEASE.ATTRIBUTE15 LS_ATTRIBUTE15 ,
  LEASE.ATTRIBUTE_CATEGORY_CODE LS_ATTRIBUTE_CATEGORY_CODE ,
  CA.CATEGORY_TYPE ,
  CA.CAPITALIZE_FLAG ,
  AD.GLOBAL_ATTRIBUTE1 ,  AD.GLOBAL_ATTRIBUTE2 ,  AD.GLOBAL_ATTRIBUTE3 ,  AD.GLOBAL_ATTRIBUTE4 ,  AD.GLOBAL_ATTRIBUTE5 ,
  AD.GLOBAL_ATTRIBUTE6 ,  AD.GLOBAL_ATTRIBUTE7 ,  AD.GLOBAL_ATTRIBUTE8 ,  AD.GLOBAL_ATTRIBUTE9 ,  AD.GLOBAL_ATTRIBUTE10 ,
  AD.GLOBAL_ATTRIBUTE11 ,  AD.GLOBAL_ATTRIBUTE12 ,  AD.GLOBAL_ATTRIBUTE13 ,  AD.GLOBAL_ATTRIBUTE14 ,  AD.GLOBAL_ATTRIBUTE15 ,
  AD.GLOBAL_ATTRIBUTE16 ,  AD.GLOBAL_ATTRIBUTE17 ,  AD.GLOBAL_ATTRIBUTE18 ,  AD.GLOBAL_ATTRIBUTE19 ,  AD.GLOBAL_ATTRIBUTE20 ,
  AD.GLOBAL_ATTRIBUTE_CATEGORY,
  AD.COMMITMENT,
  AD.INVESTMENT_LAW
FROM FA_ADDITIONS_B PAD,  -- Parent asset  -->  We need to use an alias
  FA_ADDITIONS_TL PADT,
  FA_LEASES LEASE, -- Denormalize Lease information
  PO_VENDORS PV,
  FA_CATEGORIES_B CA,
  FA_LOOKUPS_TL LUTL_PC, -- '1245/1250 PROPERTY'
  FA_LOOKUPS_B LUB_PC, -- '1245/1250 PROPERTY'
  FA_LOOKUPS_B LUB_PT, --'PROPERTY TYPE'
  FA_LOOKUPS_TL LUTL_PT, -- 'PROPERTY TYPE'
  FA_ADDITIONS_B AD,
  FA_ADDITIONS_TL ADT
WHERE AD.PARENT_ASSET_ID       = PAD.ASSET_ID(+)
AND AD.LEASE_ID                = LEASE.LEASE_ID(+)
AND PV.VENDOR_ID(+)            = LEASE.LESSOR_ID
AND AD.ASSET_CATEGORY_ID       = CA.CATEGORY_ID  --> this is a simple lookup too
AND AD.property_1245_1250_code = LUB_PC.LOOKUP_CODE(+)
AND LUB_PC.lookup_type(+)      = '1245/1250 PROPERTY'
AND LUTL_PC.LOOKUP_TYPE(+)     = '1245/1250 PROPERTY'
AND AD.property_1245_1250_code = LUTL_PC.LOOKUP_CODE(+)
AND USERENV('LANG')            = LUTL_PC.LANGUAGE(+)
AND AD.property_type_code      = LUB_PT.LOOKUP_CODE(+)
AND LUB_PT.lookup_type(+)      = 'PROPERTY TYPE'
AND LUTL_PT.LOOKUP_TYPE(+)     = 'PROPERTY TYPE'
AND AD.property_type_code      = LUTL_PT.LOOKUP_CODE(+)
AND USERENV('LANG')            = LUTL_PT.LANGUAGE(+)
AND PAD.ASSET_ID               = PADT.ASSET_ID(+)
AND PADT.LANGUAGE(+)           = userenv('LANG')
AND AD.ASSET_ID                = ADT.ASSET_ID
AND ADT.LANGUAGE               = userenv('LANG')