
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS"."FA_EID_I_MASS_TRANS_V" ("RECORD_TYPE", "MASS_SPEC", "EID_LAST_UPDATE_DATE", "REQUEST_NUM", "TRANS_NUM", "ORG_ID", "BOOK_CODE", "BOOK_NAME", "TRANS_DATE", "MAJOR_CATEGORY", "MINOR_CATEGORY", "ASSET_CATEGORY", "TRANS_DESCRIPTION", "TRANS_STATUS", "TRANS_STATUS_CODE", "TRANSFER_TYPE", "CHANGE_TYPE", "ASSET_NUMBER", "ASSET_DESCRIPTION", "ADDITION_ACCOUNTING_YEAR", "ADDITION_MONTH_YEAR", "ADDITION_COST", "ADDITION_UNITS", "ADDITION_SOURCE_NAME", "ADDITION_BATCH_ID", "ADDITION_BATCH_DATE", "ADDITION_PO_NUMBER", "ADDITION_INV_ID", "ADDITION_INV_NUMBER", "ADDITION_INV_DATE", "ADDITION_INV_LINE_NUMBER", "ADDITION_INV_DESCRIPTION", "ADDITION_SUPPLIER_NUMBER", "ADDITION_SUPPLIER_NAME", "ADDITION_PROJ_NAME", "ADDITION_PROJ_TASK", "AMORTIZED", "ATTRIBUTE_CATEGORY_CODE", "CONTEXT", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE21", "ATTRIBUTE22", "ATTRIBUTE23", "ATTRIBUTE24", "ATTRIBUTE25", "ATTRIBUTE26", "ATTRIBUTE27", "ATTRIBUTE28", "ATTRIBUTE29", "ATTRIBUTE30") AS 
  SELECT
  --ASSET TRANSFERS
  'Asset Transfer' AS RECORD_TYPE ,
  NVL(MT.CONCURRENT_REQUEST_ID, 0)
  ||'-'
  ||MT.MASS_TRANSFER_ID AS MASS_SPEC ,
  (
  CASE
    WHEN MT.CONCURRENT_REQUEST_ID IS NULL
    THEN MT.DATE_EFFECTIVE
    ELSE RS.ACTUAL_COMPLETION_DATE
  END ) EID_LAST_UPDATE_DATE ,
  MT.CONCURRENT_REQUEST_ID REQUEST_NUM ,
  MT.MASS_TRANSFER_ID TRANS_NUM ,
  NVL(BC.ORG_ID,-9999) AS ORG_ID ,
  BC.BOOK_TYPE_CODE BOOK_CODE ,
  BC.BOOK_TYPE_NAME BOOK_NAME ,
  MT.TRANSACTION_DATE_ENTERED TRANS_DATE,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'BASED_CATEGORY', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'FULL_DESCRIPTION') ) MAJOR_CATEGORY ,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'MINOR_CATEGORY', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'FULL_DESCRIPTION')) MINOR_CATEGORY,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'ALL', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'FULL_DESCRIPTION')) ASSET_CATEGORY ,
  MT.DESCRIPTION TRANS_DESCRIPTION,
  (
  CASE
    WHEN RS.USER_CONCURRENT_PROGRAM_NAME = 'Mass Transfers Preview Report'
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='MASS_TRX_STATUS'
      AND LOOKUP_CODE  ='PREVIEWED'
      )
    WHEN RS.USER_CONCURRENT_PROGRAM_NAME ='Mass Transfer'
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='MASS_TRX_STATUS'
      AND LOOKUP_CODE  ='COMPLETED'
      )
    WHEN MT.CONCURRENT_REQUEST_ID IS NULL
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='MASS_TRX_STATUS'
      AND LOOKUP_CODE  ='NEW'
      )
  END) TRANS_STATUS ,
  (
  CASE
    WHEN RS.USER_CONCURRENT_PROGRAM_NAME = 'Mass Transfers Preview Report'
    THEN 'PREVIEWED'
    WHEN RS.USER_CONCURRENT_PROGRAM_NAME ='Mass Transfer'
    THEN 'COMPLETED'
    WHEN MT.CONCURRENT_REQUEST_ID IS NULL
    THEN 'NEW'
  END) TRANS_STATUS_CODE
  -- TRANSFER TYPE , WILL BE MULTI-ASSIGN ATTRIBUTE IN ENDECA METADATA
  ,
  (
  CASE
    WHEN MT.FROM_LOCATION_ID <> MT.TO_LOCATION_ID
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_TRANSFER_TYPE'
      AND LOOKUP_CODE  ='LOCATION_TRANSFER'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MT.FROM_GL_CCID<> MT.TO_GL_CCID
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_TRANSFER_TYPE'
      AND LOOKUP_CODE  ='DEPRECIATION_EXPENSE_TRANSFER'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MT.FROM_EMPLOYEE_ID <> MT.TO_EMPLOYEE_ID
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_TRANSFER_TYPE'
      AND LOOKUP_CODE  ='EMPLOYEE_TRANSFER'
      )
    ELSE
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_TRANSFER_TYPE'
      AND LOOKUP_CODE  ='NO_TRANSFER_DET'
      )
  END) AS TRANSFER_TYPE
  /* UNION ATTRIBUTES*/
  ,
  ''            AS CHANGE_TYPE ,
  ''            AS ASSET_NUMBER ,
  ''            AS ASSET_DESCRIPTION ,
  ''            AS ADDITION_ACCOUNTING_YEAR ,
  ''            AS ADDITION_MONTH_YEAR ,
  TO_NUMBER('') AS ADDITION_COST ,
  TO_NUMBER('') AS ADDITION_UNITS ,
  ''            AS ADDITION_SOURCE_NAME ,
  TO_NUMBER('') AS ADDITION_BATCH_ID ,
  TO_DATE('')   AS ADDITION_BATCH_DATE ,
  ''            AS ADDITION_PO_NUMBER ,
  TO_NUMBER('') AS ADDITION_INV_ID ,
  ''            AS ADDITION_INV_NUMBER ,
  TO_DATE('')   AS ADDITION_INV_DATE ,
  TO_NUMBER('') AS ADDITION_INV_LINE_NUMBER ,
  ''            AS ADDITION_INV_DESCRIPTION ,
  ''            AS ADDITION_SUPPLIER_NUMBER ,
  ''            AS ADDITION_SUPPLIER_NAME ,
  ''            AS ADDITION_PROJ_NAME ,
  ''            AS ADDITION_PROJ_TASK ,
  ''            AS AMORTIZED
  --ASSET TRANSFER DFF
  ,
  MT.ATTRIBUTE_CATEGORY_CODE ,
  NULL AS CONTEXT ,
  MT.ATTRIBUTE1 ,
  MT.ATTRIBUTE2 ,
  MT.ATTRIBUTE3 ,
  MT.ATTRIBUTE4 ,
  MT.ATTRIBUTE5 ,
  MT.ATTRIBUTE6 ,
  MT.ATTRIBUTE7 ,
  MT.ATTRIBUTE8 ,
  MT.ATTRIBUTE9 ,
  MT.ATTRIBUTE10 ,
  MT.ATTRIBUTE11 ,
  MT.ATTRIBUTE12 ,
  MT.ATTRIBUTE13 ,
  MT.ATTRIBUTE14 ,
  MT.ATTRIBUTE15 ,
  NULL AS ATTRIBUTE16 ,
  NULL AS ATTRIBUTE17 ,
  NULL AS ATTRIBUTE18 ,
  NULL AS ATTRIBUTE19 ,
  NULL AS ATTRIBUTE20 ,
  NULL AS ATTRIBUTE21 ,
  NULL AS ATTRIBUTE22 ,
  NULL AS ATTRIBUTE23 ,
  NULL AS ATTRIBUTE24 ,
  NULL AS ATTRIBUTE25 ,
  NULL AS ATTRIBUTE26 ,
  NULL AS ATTRIBUTE27 ,
  NULL AS ATTRIBUTE28 ,
  NULL AS ATTRIBUTE29 ,
  NULL AS ATTRIBUTE30
FROM FA_MASS_TRANSFERS MT,
  FA_BOOK_CONTROLS BC,
  FA_CATEGORIES_B FC,
  FND_CONC_REQ_SUMMARY_V RS ,
  FA_SYSTEM_CONTROLS FSC,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND  RECORD_TYPE           = 'fa'
  AND ETL_RUN_STATUS        = 'S'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) LAST_RUN,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) CURRENT_RUN
WHERE MT.BOOK_TYPE_CODE                         = BC.BOOK_TYPE_CODE
AND BC.BOOK_CLASS                               = 'CORPORATE'
AND BC.DATE_INEFFECTIVE                        IS NULL
AND MT.CATEGORY_ID                              = FC.CATEGORY_ID(+)
AND MT.CONCURRENT_REQUEST_ID                    = RS.REQUEST_ID(+)
AND NVL(RS.USER_CONCURRENT_PROGRAM_NAME, '$$') <> 'Mass Transfer'
AND ((MT.CONCURRENT_REQUEST_ID                 IS NULL
AND ( (MT.DATE_EFFECTIVE                       >= LAST_RUN.ETL_RUN_START_DATE
AND MT.DATE_EFFECTIVE                           < CURRENT_RUN.ETL_RUN_START_DATE )))
OR ( (RS.ACTUAL_COMPLETION_DATE                >= LAST_RUN.ETL_RUN_START_DATE
AND RS.ACTUAL_COMPLETION_DATE                   < CURRENT_RUN.ETL_RUN_START_DATE )))
UNION ALL
-- Asset Revaluation
SELECT 'Asset revaluation' AS RECORD_TYPE,
  NVL(MR.LAST_REQUEST_ID,0)
  ||'-'
  ||MR.MASS_REVAL_ID
  ||'-'
  ||MRR.ASSET_ID AS MASS_SPEC,
  MR.LAST_UPDATE_DATE EID_LAST_UPDATE_DATE,
  MR.LAST_REQUEST_ID REQUEST_NUM,
  MR.MASS_REVAL_ID TRANS_NUM,
  NVL(BC.ORG_ID,-9999) AS ORG_ID,
  BC.BOOK_TYPE_CODE BOOK_CODE,
  BC.BOOK_TYPE_NAME BOOK_NAME,
  MR.REVAL_DATE TRANS_DATE,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'BASED_CATEGORY', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'FULL_DESCRIPTION') ) MAJOR_CATEGORY ,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'MINOR_CATEGORY', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'FULL_DESCRIPTION')) MINOR_CATEGORY,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'ALL', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'FULL_DESCRIPTION')) ASSET_CATEGORY ,
  MR.DESCRIPTION TRANS_DESCRIPTION ,
  LO.MEANING AS TRANS_STATUS ,
  MR.STATUS  AS TRANS_STATUS_CODE ,
  ''         AS TRANSFER_TYPE ,
  ''         AS CHANGE_TYPE
  /* UNION ATTRIBUTES*/
  ,
  AD.ASSET_NUMBER AS ASSET_NUMBER ,
  ''              AS ASSET_DESCRIPTION ,
  ''              AS ADDITION_ACCOUNTING_YEAR ,
  ''              AS ADDITION_MONTH_YEAR ,
  TO_NUMBER('')   AS ADDITION_COST ,
  TO_NUMBER('')   AS ADDITION_UNITS ,
  ''              AS ADDITION_SOURCE_NAME ,
  TO_NUMBER('')   AS ADDITION_BATCH_ID ,
  TO_DATE('')     AS ADDITION_BATCH_DATE ,
  ''              AS ADDITION_PO_NUMBER ,
  TO_NUMBER('')   AS ADDITION_INV_ID ,
  ''              AS ADDITION_INV_NUMBER ,
  TO_DATE('')     AS ADDITION_INV_DATE ,
  TO_NUMBER('')   AS ADDITION_INV_LINE_NUMBER ,
  ''              AS ADDITION_INV_DESCRIPTION ,
  ''              AS ADDITION_SUPPLIER_NUMBER ,
  ''              AS ADDITION_SUPPLIER_NAME ,
  ''              AS ADDITION_PROJ_NAME ,
  ''              AS ADDITION_PROJ_TASK ,
  ''              AS AMORTIZED
  --MASS REVALUATION DFF
  ,
  MR.ATTRIBUTE_CATEGORY_CODE ,
  NULL AS CONTEXT ,
  MR.ATTRIBUTE1 ,
  MR.ATTRIBUTE2 ,
  MR.ATTRIBUTE3 ,
  MR.ATTRIBUTE4 ,
  MR.ATTRIBUTE5 ,
  MR.ATTRIBUTE6 ,
  MR.ATTRIBUTE7 ,
  MR.ATTRIBUTE8 ,
  MR.ATTRIBUTE9 ,
  MR.ATTRIBUTE10 ,
  MR.ATTRIBUTE11 ,
  MR.ATTRIBUTE12 ,
  MR.ATTRIBUTE13 ,
  MR.ATTRIBUTE14 ,
  MR.ATTRIBUTE15 ,
  NULL AS ATTRIBUTE16 ,
  NULL AS ATTRIBUTE17 ,
  NULL AS ATTRIBUTE18 ,
  NULL AS ATTRIBUTE19 ,
  NULL AS ATTRIBUTE20 ,
  NULL AS ATTRIBUTE21 ,
  NULL AS ATTRIBUTE22 ,
  NULL AS ATTRIBUTE23 ,
  NULL AS ATTRIBUTE24 ,
  NULL AS ATTRIBUTE25 ,
  NULL AS ATTRIBUTE26 ,
  NULL AS ATTRIBUTE27 ,
  NULL AS ATTRIBUTE28 ,
  NULL AS ATTRIBUTE29 ,
  NULL AS ATTRIBUTE30
FROM FA_MASS_REVALUATIONS MR,
  FA_MASS_REVALUATION_RULES MRR,
  FA_BOOK_CONTROLS BC,
  FA_CATEGORIES_B FC ,
  FA_ADDITIONS_B AD,
  FA_SYSTEM_CONTROLS FSC,
  FA_LOOKUPS LO,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_STATUS        = 'S'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) LAST_RUN,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) CURRENT_RUN
WHERE MR.MASS_REVAL_ID       = MRR.MASS_REVAL_ID(+)
AND MR.BOOK_TYPE_CODE        = BC.BOOK_TYPE_CODE
AND BC.BOOK_CLASS            = 'CORPORATE'
AND BC.DATE_INEFFECTIVE     IS NULL
AND MRR.CATEGORY_ID          = FC.CATEGORY_ID(+)
AND MRR.ASSET_ID             = AD.ASSET_ID(+)
AND MR.STATUS               <> ('COMPLETED')
AND LO.LOOKUP_TYPE           ='MASS_TRX_STATUS'
AND LO.ENABLED_FLAG          ='Y'
AND MR.STATUS                = LO.LOOKUP_CODE
AND ( ( MR.LAST_UPDATE_DATE >= LAST_RUN.ETL_RUN_START_DATE
AND MR.LAST_UPDATE_DATE      < CURRENT_RUN.ETL_RUN_START_DATE ))
UNION ALL
-- ASSET CHANGES
SELECT 'Asset Change' AS RECORD_TYPE,
  NVL(MC.CONCURRENT_REQUEST_ID,0)
  ||'-'
  ||MC.MASS_CHANGE_ID AS MASS_SPEC,
  MC.LAST_UPDATE_DATE EID_LAST_UPDATE_DATE,
  MC.CONCURRENT_REQUEST_ID REQUEST_NUM,
  MC.MASS_CHANGE_ID TRANS_NUM,
  NVL(BC.ORG_ID,-9999) AS ORG_ID,
  BC.BOOK_TYPE_CODE BOOK_CODE,
  BC.BOOK_TYPE_NAME BOOK_NAME,
  MC.TRANSACTION_DATE_ENTERED TRANS_DATE,
  ''         AS ASSET_CATEGORY,
  ''         AS MAJOR_CATEGORY,
  ''         AS MINOR_CATEGORY,
  ''         AS TRANS_DESCRIPTION ,
  LO.MEANING AS TRANS_STATUS ,
  MC.STATUS  AS TRANS_STATUS_CODE ,
  ''         AS TRANSFER_TYPE ,
  (
  CASE
    WHEN MC.FROM_DATE_PLACED_IN_SERVICE <> MC.TO_DATE_PLACED_IN_SERVICE
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='DPIS_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_CONVENTION <> MC.TO_CONVENTION
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='PRORATE_CONVENTION_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_LIFE_IN_MONTHS <> MC.TO_LIFE_IN_MONTHS
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='ASSET_LIFE_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_METHOD_CODE <> MC.TO_METHOD_CODE
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='DEPRECIATION_METHOD_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_BASIC_RATE <> MC.FROM_ADJUSTED_RATE
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='DEPRECIATION_RATE_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_PRODUCTION_CAPACITY <> MC.TO_PRODUCTION_CAPACITY
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='PRODUCTION_CAPACITY_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_UOM <> MC.TO_UOM
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='UNIT_CHANGE'
      )
      ||'|'
    ELSE ''
  END )
  || (
  CASE
    WHEN MC.FROM_GROUP_ASSOCIATION <> MC.TO_GROUP_ASSOCIATION
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='GROUP_ASSOCIATION_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_SALVAGE_TYPE        <> MC.TO_SALVAGE_TYPE
    OR MC.FROM_PERCENT_SALVAGE_VALUE <> MC.TO_PERCENT_SALVAGE_VALUE
    OR MC.FROM_SALVAGE_VALUE         <> MC.FROM_SALVAGE_VALUE
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='SALVAGE_VALUE_CHANGE'
      )
      ||'|'
    ELSE ''
  END)
  || (
  CASE
    WHEN MC.FROM_DEPRN_LIMIT_TYPE <> MC.TO_DEPRN_LIMIT_TYPE
    OR MC.TO_DEPRN_LIMIT          <> MC.TO_DEPRN_LIMIT
    OR MC.FROM_DEPRN_LIMIT_AMOUNT <> MC.TO_DEPRN_LIMIT_AMOUNT
    THEN
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='DEPRECIATION_LIMIT_CHANGE'
      )
    ELSE
      (SELECT MEANING
      FROM FA_LOOKUPS
      WHERE LOOKUP_TYPE='FA_EID_MASS_CHANGE_TYPE'
      AND LOOKUP_CODE  ='NO_CHANGE_DET'
      )
  END ) AS CHANGE_TYPE
  /* UNION ATTRIBUTES*/
  ,
  ''            AS ASSET_NUMBER ,
  ''            AS ASSET_DESCRIPTION ,
  ''            AS ADDITION_ACCOUNTING_YEAR ,
  ''            AS ADDITION_MONTH_YEAR ,
  TO_NUMBER('') AS ADDITION_COST ,
  TO_NUMBER('') AS ADDITION_UNITS ,
  ''            AS ADDITION_SOURCE_NAME ,
  TO_NUMBER('') AS ADDITION_BATCH_ID ,
  TO_DATE('')   AS ADDITION_BATCH_DATE ,
  ''            AS ADDITION_PO_NUMBER ,
  TO_NUMBER('') AS ADDITION_INV_ID ,
  ''            AS ADDITION_INV_NUMBER ,
  TO_DATE('')   AS ADDITION_INV_DATE ,
  TO_NUMBER('') AS ADDITION_INV_LINE_NUMBER ,
  ''            AS ADDITION_INV_DESCRIPTION ,
  ''            AS ADDITION_SUPPLIER_NUMBER ,
  ''            AS ADDITION_SUPPLIER_NAME ,
  ''            AS ADDITION_PROJ_NAME ,
  ''            AS ADDITION_PROJ_TASK ,
  MC.AMORTIZE_FLAG AMORTIZED
  --MASS CHANGE DFF
  ,
  MC.ATTRIBUTE_CATEGORY_CODE ,
  NULL AS CONTEXT ,
  MC.ATTRIBUTE1 ,
  MC.ATTRIBUTE2 ,
  MC.ATTRIBUTE3 ,
  MC.ATTRIBUTE4 ,
  MC.ATTRIBUTE5 ,
  MC.ATTRIBUTE6 ,
  MC.ATTRIBUTE7 ,
  MC.ATTRIBUTE8 ,
  MC.ATTRIBUTE9 ,
  MC.ATTRIBUTE10 ,
  MC.ATTRIBUTE11 ,
  MC.ATTRIBUTE12 ,
  MC.ATTRIBUTE13 ,
  MC.ATTRIBUTE14 ,
  MC.ATTRIBUTE15 ,
  NULL AS ATTRIBUTE16 ,
  NULL AS ATTRIBUTE17 ,
  NULL AS ATTRIBUTE18 ,
  NULL AS ATTRIBUTE19 ,
  NULL AS ATTRIBUTE20 ,
  NULL AS ATTRIBUTE21 ,
  NULL AS ATTRIBUTE22 ,
  NULL AS ATTRIBUTE23 ,
  NULL AS ATTRIBUTE24 ,
  NULL AS ATTRIBUTE25 ,
  NULL AS ATTRIBUTE26 ,
  NULL AS ATTRIBUTE27 ,
  NULL AS ATTRIBUTE28 ,
  NULL AS ATTRIBUTE29 ,
  NULL AS ATTRIBUTE30
FROM FA_MASS_CHANGES MC,
  FA_BOOK_CONTROLS BC,
  FA_LOOKUPS LO,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_STATUS        = 'S'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) LAST_RUN,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) CURRENT_RUN
WHERE MC.BOOK_TYPE_CODE      = BC.BOOK_TYPE_CODE
AND BC.BOOK_CLASS            = 'CORPORATE'
AND BC.DATE_INEFFECTIVE     IS NULL
AND MC.STATUS               <> 'COMPLETED'
AND LO.LOOKUP_TYPE           ='MASS_TRX_STATUS'
AND LO.ENABLED_FLAG          ='Y'
AND MC.STATUS                = LO.LOOKUP_CODE
AND ( ( MC.LAST_UPDATE_DATE >= LAST_RUN.ETL_RUN_START_DATE
AND MC.LAST_UPDATE_DATE      < CURRENT_RUN.ETL_RUN_START_DATE ))
UNION ALL
-- Asset Reclassification

SELECT 'Asset Reclass' AS RECORD_TYPE,
  NVL(MR.CONCURRENT_REQUEST_ID, 0)
  ||'-'
  ||MR.MASS_RECLASS_ID AS MASS_SPEC,
  MR.LAST_UPDATE_DATE EID_LAST_UPDATE_DATE,
  MR.CONCURRENT_REQUEST_ID REQUEST_NUM,
  MR.MASS_RECLASS_ID TRANS_NUM,
  NVL(BC.ORG_ID,-9999) AS ORG_ID,
  MR.BOOK_TYPE_CODE BOOK_CODE,
  BC.BOOK_TYPE_NAME BOOK_NAME,
  MR.TRANSACTION_DATE_ENTERED TRANS_DATE,
  '' AS ASSET_CATEGORY,
  '' AS MAJOR_CATEGORY,
  '' AS MINOR_CATEGORY,
  '' AS TRANS_DESCRIPTION ,
  LO.MEANING TRANS_STATUS ,
  MR.STATUS TRANS_STATUS_CODE ,
  '' AS TRANSFER_TYPE ,
  '' AS CHANGE_TYPE
  /* UNION ATTRIBUTES*/
  ,
  ''            AS ASSET_NUMBER ,
  ''            AS ASSET_DESCRIPTION ,
  ''            AS ADDITION_ACCOUNTING_YEAR ,
  ''            AS ADDITION_MONTH_YEAR ,
  TO_NUMBER('') AS ADDITION_COST ,
  TO_NUMBER('') AS ADDITION_UNITS ,
  ''            AS ADDITION_SOURCE_NAME ,
  TO_NUMBER('') AS ADDITION_BATCH_ID ,
  TO_DATE('')   AS ADDITION_BATCH_DATE ,
  ''            AS ADDITION_PO_NUMBER ,
  TO_NUMBER('') AS ADDITION_INV_ID ,
  ''            AS ADDITION_INV_NUMBER ,
  TO_DATE('')   AS ADDITION_INV_DATE ,
  TO_NUMBER('') AS ADDITION_INV_LINE_NUMBER ,
  ''            AS ADDITION_INV_DESCRIPTION ,
  ''            AS ADDITION_SUPPLIER_NUMBER ,
  ''            AS ADDITION_SUPPLIER_NAME ,
  ''            AS ADDITION_PROJ_NAME ,
  ''            AS ADDITION_PROJ_TASK ,
  MR.AMORTIZE_FLAG AMORTIZED
  --MASS RECLASSIFICATION DFF
  ,
  MR.ATTRIBUTE_CATEGORY_CODE ,
  NULL AS CONTEXT ,
  MR.ATTRIBUTE1 ,
  MR.ATTRIBUTE2 ,
  MR.ATTRIBUTE3 ,
  MR.ATTRIBUTE4 ,
  MR.ATTRIBUTE5 ,
  MR.ATTRIBUTE6 ,
  MR.ATTRIBUTE7 ,
  MR.ATTRIBUTE8 ,
  MR.ATTRIBUTE9 ,
  MR.ATTRIBUTE10 ,
  MR.ATTRIBUTE11 ,
  MR.ATTRIBUTE12 ,
  MR.ATTRIBUTE13 ,
  MR.ATTRIBUTE14 ,
  MR.ATTRIBUTE15 ,
  NULL AS ATTRIBUTE16 ,
  NULL AS ATTRIBUTE17 ,
  NULL AS ATTRIBUTE18 ,
  NULL AS ATTRIBUTE19 ,
  NULL AS ATTRIBUTE20 ,
  NULL AS ATTRIBUTE21 ,
  NULL AS ATTRIBUTE22 ,
  NULL AS ATTRIBUTE23 ,
  NULL AS ATTRIBUTE24 ,
  NULL AS ATTRIBUTE25 ,
  NULL AS ATTRIBUTE26 ,
  NULL AS ATTRIBUTE27 ,
  NULL AS ATTRIBUTE28 ,
  NULL AS ATTRIBUTE29 ,
  NULL AS ATTRIBUTE30
FROM FA_MASS_RECLASS MR,
  FA_BOOK_CONTROLS BC,
  FA_LOOKUPS LO,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_STATUS        = 'S'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) LAST_RUN,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) CURRENT_RUN
WHERE MR.BOOK_TYPE_CODE      = BC.BOOK_TYPE_CODE
AND BC.BOOK_CLASS            = 'CORPORATE'
AND BC.DATE_INEFFECTIVE     IS NULL
AND MR.STATUS               <> 'COMPLETED'
AND LO.LOOKUP_TYPE           ='MASS_TRX_STATUS'
AND LO.ENABLED_FLAG          ='Y'
AND MR.STATUS                = LO.LOOKUP_CODE
AND ( ( MR.LAST_UPDATE_DATE >= LAST_RUN.ETL_RUN_START_DATE
AND MR.LAST_UPDATE_DATE      < CURRENT_RUN.ETL_RUN_START_DATE ))
UNION ALL
-- ASSET MASS RETIREMENTS
SELECT 'Asset Retirement' AS RECORD_TYPE,
  NVL(MT.RETIRE_REQUEST_ID,0)
  ||'-'
  ||MT.MASS_RETIREMENT_ID AS MASS_SPEC,
  MT.LAST_UPDATE_DATE EID_LAST_UPDATE_DATE,
  MT.RETIRE_REQUEST_ID REQUEST_NUM,
  MT.MASS_RETIREMENT_ID TRANS_NUM,
  NVL(BC.ORG_ID,-9999) AS ORG_ID,
  MT.BOOK_TYPE_CODE BOOK_CODE,
  BC.BOOK_TYPE_NAME BOOK_NAME,
  MT.RETIREMENT_DATE TRANS_DATE,
  '' AS ASSET_CATEGORY,
  '' AS MAJOR_CATEGORY,
  '' AS MINOR_CATEGORY,
  '' AS TRANS_DESCRIPTION ,
  LO.MEANING TRANS_STATUS ,
  MT.STATUS TRANS_STATUS_CODE ,
  '' AS TRANSFER_TYPE ,
  '' AS CHANGE_TYPE
  /* UNION ATTRIBUTES*/
  ,
  ''            AS ASSET_NUMBER ,
  ''            AS ASSET_DESCRIPTION ,
  ''            AS ADDITION_ACCOUNTING_YEAR ,
  ''            AS ADDITION_MONTH_YEAR ,
  TO_NUMBER('') AS ADDITION_COST ,
  TO_NUMBER('') AS ADDITION_UNITS ,
  ''            AS ADDITION_SOURCE_NAME ,
  TO_NUMBER('') AS ADDITION_BATCH_ID ,
  TO_DATE('')   AS ADDITION_BATCH_DATE ,
  ''            AS ADDITION_PO_NUMBER ,
  TO_NUMBER('') AS ADDITION_INV_ID ,
  ''            AS ADDITION_INV_NUMBER ,
  TO_DATE('')   AS ADDITION_INV_DATE ,
  TO_NUMBER('') AS ADDITION_INV_LINE_NUMBER ,
  ''            AS ADDITION_INV_DESCRIPTION ,
  ''            AS ADDITION_SUPPLIER_NUMBER ,
  ''            AS ADDITION_SUPPLIER_NAME ,
  ''            AS ADDITION_PROJ_NAME ,
  ''            AS ADDITION_PROJ_TASK ,
  ''            AS AMORTIZED
  --MASS RETIREMENTS DFF
  ,
  MT.ATTRIBUTE_CATEGORY_CODE ,
  NULL AS CONTEXT ,
  MT.ATTRIBUTE1 ,
  MT.ATTRIBUTE2 ,
  MT.ATTRIBUTE3 ,
  MT.ATTRIBUTE4 ,
  MT.ATTRIBUTE5 ,
  MT.ATTRIBUTE6 ,
  MT.ATTRIBUTE7 ,
  MT.ATTRIBUTE8 ,
  MT.ATTRIBUTE9 ,
  MT.ATTRIBUTE10 ,
  MT.ATTRIBUTE11 ,
  MT.ATTRIBUTE12 ,
  MT.ATTRIBUTE13 ,
  MT.ATTRIBUTE14 ,
  MT.ATTRIBUTE15 ,
  NULL AS ATTRIBUTE16 ,
  NULL AS ATTRIBUTE17 ,
  NULL AS ATTRIBUTE18 ,
  NULL AS ATTRIBUTE19 ,
  NULL AS ATTRIBUTE20 ,
  NULL AS ATTRIBUTE21 ,
  NULL AS ATTRIBUTE22 ,
  NULL AS ATTRIBUTE23 ,
  NULL AS ATTRIBUTE24 ,
  NULL AS ATTRIBUTE25 ,
  NULL AS ATTRIBUTE26 ,
  NULL AS ATTRIBUTE27 ,
  NULL AS ATTRIBUTE28 ,
  NULL AS ATTRIBUTE29 ,
  NULL AS ATTRIBUTE30
FROM FA_MASS_RETIREMENTS MT,
  FA_BOOK_CONTROLS BC,
  FA_LOOKUPS LO,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_STATUS        = 'S'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) LAST_RUN,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) CURRENT_RUN
WHERE MT.BOOK_TYPE_CODE      = BC.BOOK_TYPE_CODE
AND BC.BOOK_CLASS            = 'CORPORATE'
AND BC.DATE_INEFFECTIVE     IS NULL
AND MT.STATUS               <> 'COMPLETED'
AND LO.LOOKUP_TYPE           ='MASS_TRX_STATUS'
AND LO.ENABLED_FLAG          ='Y'
AND MT.STATUS                = LO.LOOKUP_CODE
AND ( ( MT.LAST_UPDATE_DATE >= LAST_RUN.ETL_RUN_START_DATE
AND MT.LAST_UPDATE_DATE      < CURRENT_RUN.ETL_RUN_START_DATE ))
UNION ALL
-- ASSETS MASS ADDITIONS
SELECT 'Mass Additions' AS RECORD_TYPE,
  MA.MASS_ADDITION_ID
  || '' AS MASS_SPEC,
  NVL(MA.LAST_UPDATE_DATE,MA.CREATION_DATE) EID_LAST_UPDATE_DATE,
  TO_NUMBER('')         AS REQUEST_NUM,
  TO_NUMBER('')         AS TRANS_NUM,
  NVL(FBC.ORG_ID,-9999) AS ORG_ID,
  MA.BOOK_TYPE_CODE     AS BOOK_CODE,
  FBC.BOOK_TYPE_NAME BOOK_NAME,
  MA.ACCOUNTING_DATE AS TRANS_DATE,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'BASED_CATEGORY', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'DESCRIPTION') ) MAJOR_CATEGORY ,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'MINOR_CATEGORY', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'DESCRIPTION')) MINOR_CATEGORY,
  DECODE(FC.CATEGORY_ID,NULL,NULL, FND_FLEX_XML_PUBLISHER_APIS.PROCESS_KFF_COMBINATION_1(P_LEXICAL_NAME => 'ASSETCATEGORY' , P_APPLICATION_SHORT_NAME => 'OFA', P_ID_FLEX_CODE => 'CAT#', P_ID_FLEX_NUM => FSC.CATEGORY_FLEX_STRUCTURE, P_DATA_SET => FSC.CATEGORY_FLEX_STRUCTURE, P_CCID => FC.CATEGORY_ID, P_SEGMENTS => 'ALL', P_SHOW_PARENT_SEGMENTS => 'N', P_OUTPUT_TYPE=>'DESCRIPTION')) ASSET_CATEGORY ,
  '' AS TRANS_DESCRIPTION ,
  LO.MEANING TRANS_STATUS ,
  MA.QUEUE_NAME                         AS TRANS_STATUS_CODE ,
  ''                                    AS TRANSFER_TYPE ,
  ''                                    AS CHANGE_TYPE ,
  MA.ASSET_NUMBER                       AS ASSET_NUMBER ,
  MA.DESCRIPTION                        AS ASSET_DESCRIPTION ,
  TO_CHAR(MA.ACCOUNTING_DATE,'YYYY')    AS ADDITION_ACCOUNTING_YEAR ,
  TO_CHAR(MA.ACCOUNTING_DATE,'MM-YYYY') AS ADDITION_MONTH_YEAR ,
  MA.FIXED_ASSETS_COST                  AS ADDITION_COST ,
  MA.FIXED_ASSETS_UNITS                 AS ADDITION_UNITS ,
  MA.FEEDER_SYSTEM_NAME                 AS ADDITION_SOURCE_NAME
  --PAYABLE MASS ADDITION
  ,
  MA.CREATE_BATCH_ID     AS ADDITION_BATCH_ID ,
  MA.CREATE_BATCH_DATE   AS ADDITION_BATCH_DATE ,
  MA.PO_NUMBER           AS ADDITION_PO_NUMBER ,
  MA.INVOICE_ID          AS ADDITION_INV_ID ,
  MA.INVOICE_NUMBER      AS ADDITION_INV_NUMBER ,
  MA.INVOICE_DATE        AS ADDITION_INV_DATE ,
  MA.INVOICE_LINE_NUMBER AS ADDITION_INV_LINE_NUMBER ,
  MA.DESCRIPTION         AS ADDITION_INV_DESCRIPTION ,
  PO.SEGMENT1            AS ADDITION_SUPPLIER_NUMBER ,
  PO.VENDOR_NAME         AS ADDITION_SUPPLIER_NAME
  -- PROJECT MASS ADDITION
  ,
  PJ.NAME        AS ADDITION_PROJ_NAME ,
  PT.TASK_NUMBER AS ADDITION_PROJ_TASK ,
  MA.AMORTIZE_FLAG AMORTIZED
  --MASS ADDITIONS DFF
  ,
  MA.ATTRIBUTE_CATEGORY_CODE ,
  MA.CONTEXT ,
  MA.ATTRIBUTE1 ,
  MA.ATTRIBUTE2 ,
  MA.ATTRIBUTE3 ,
  MA.ATTRIBUTE4 ,
  MA.ATTRIBUTE5 ,
  MA.ATTRIBUTE6 ,
  MA.ATTRIBUTE7 ,
  MA.ATTRIBUTE8 ,
  MA.ATTRIBUTE9 ,
  MA.ATTRIBUTE10 ,
  MA.ATTRIBUTE11 ,
  MA.ATTRIBUTE12 ,
  MA.ATTRIBUTE13 ,
  MA.ATTRIBUTE14 ,
  MA.ATTRIBUTE15 ,
  MA.ATTRIBUTE16 ,
  MA.ATTRIBUTE17 ,
  MA.ATTRIBUTE18 ,
  MA.ATTRIBUTE19 ,
  MA.ATTRIBUTE20 ,
  MA.ATTRIBUTE21 ,
  MA.ATTRIBUTE22 ,
  MA.ATTRIBUTE23 ,
  MA.ATTRIBUTE24 ,
  MA.ATTRIBUTE25 ,
  MA.ATTRIBUTE26 ,
  MA.ATTRIBUTE27 ,
  MA.ATTRIBUTE28 ,
  MA.ATTRIBUTE29 ,
  MA.ATTRIBUTE30
FROM AP_SUPPLIERS PO ,
  FA_ADDITIONS_B AD ,
  FA_MASS_ADDITIONS MA ,
  FA_WARRANTIES WAR ,
  FA_ADDITIONS_B GAD ,
  PA_PROJECTS_ALL PJ ,
  PA_TASKS PT ,
  FA_CATEGORIES_B FC ,
  FA_BOOK_CONTROLS FBC ,
  FA_DEPRN_PERIODS FDP1 ,
  FA_DEPRN_PERIODS FDP2 ,
  GL_LEDGERS LGR ,
  FA_SYSTEM_CONTROLS FSC ,
  FA_LOOKUPS LO ,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_STATUS        = 'S'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) LAST_RUN ,
  (SELECT MAX (ETL_RUN_START_DATE) ETL_RUN_START_DATE
  FROM FND_EID_ETL_AUDITS
  WHERE EID_DATA_STORE_NAME = 'fa'
  AND RECORD_TYPE           = 'fa'
  AND ETL_RUN_LANG=USERENV('LANG')
  ) CURRENT_RUN
WHERE FBC.BOOK_TYPE_CODE        = FDP1.BOOK_TYPE_CODE
AND FBC.BOOK_CLASS              = 'CORPORATE'
AND FBC.DATE_INEFFECTIVE       IS NULL
AND FBC.SET_OF_BOOKS_ID         = LGR.LEDGER_ID
AND LGR.OBJECT_TYPE_CODE        = 'L'
AND NVL(LGR.COMPLETE_FLAG, 'Y') = 'Y'
AND FBC.LAST_PERIOD_COUNTER     = FDP1.PERIOD_COUNTER
AND FBC.BOOK_TYPE_CODE          = FDP2.BOOK_TYPE_CODE
AND FBC.LAST_PERIOD_COUNTER+1   = FDP2.PERIOD_COUNTER
AND FBC.DATE_INEFFECTIVE       IS NULL
AND MA.BOOK_TYPE_CODE           = FBC.BOOK_TYPE_CODE
AND MA.ASSET_CATEGORY_ID        = FC.CATEGORY_ID (+)
AND MA.PROJECT_ID               = PJ.PROJECT_ID ( + )
AND MA.TASK_ID                  = PT.TASK_ID (    + )
AND MA.PO_VENDOR_ID             = PO.VENDOR_ID (  + )
AND MA.PARENT_ASSET_ID          = AD.ASSET_ID (   + )
AND MA.WARRANTY_ID              = WAR.WARRANTY_ID (+)
AND GAD.ASSET_ID (+)            = MA.GROUP_ASSET_ID
AND NVL(MA.POSTING_STATUS, 'A')  not in   ('POSTED','SPLIT')
 AND ma.queue_name = lo.lookup_code
 AND lo.LOOKUP_TYPE   = 'QUEUE NAME'
 and lo.enabled_flag='Y'
AND MA.POST_BATCH_ID           IS NULL
And ( (  Nvl(Ma.Last_Update_Date,Ma.Creation_Date)    >= Last_Run.Etl_Run_Start_Date
AND  NVL(MA.LAST_UPDATE_DATE,MA.CREATION_DATE)         < CURRENT_RUN.ETL_RUN_START_DATE ))
   ;
