SELECT * FROM all_views WHERE view_name = 'FA_FINANCIAL_INQUIRY_COST_V';

-- The grain is at FA_BOOKS
-- Use transaction Date to lookup FA Period
-- the calendar type is determined by the FK Book type
-- use effective date from transaction table to lookup depreciation period
SELECT BK.TRANSACTION_HEADER_ID_IN TRANSACTION_HEADER_ID_IN ,
  BK.ASSET_ID ,
  AD.ASSET_NUMBER ,
  BK.BOOK_TYPE_CODE ,
  LO.MEANING TRANSACTION_TYPE ,
  DP.PERIOD_NAME PERIOD_ENTERED ,
  CP.PERIOD_NAME PERIOD_EFFECTIVE ,
  BK.COST CURRENT_COST ,
  TH.TRANSACTION_DATE_ENTERED ,
  DP.FISCAL_YEAR
FROM FA_ADDITIONS_B AD ,
  FA_DEPRN_PERIODS DP ,
  FA_CALENDAR_PERIODS CP,
  FA_BOOK_CONTROLS BC,
  FA_LOOKUPS LO ,
  FA_TRANSACTION_HEADERS TH ,
  FA_BOOKS_BAS BKPREV ,
  FA_BOOKS BK
WHERE (BKPREV.TRANSACTION_HEADER_ID_OUT(+) = BK.TRANSACTION_HEADER_ID_IN
AND NVL(BKPREV.COST,BK.COST-1)            != BK.COST)
AND (LO.LOOKUP_TYPE                        = 'FAXOLTRX'
AND LO.LOOKUP_CODE                         = TH.TRANSACTION_TYPE_CODE)
AND BC.BOOK_TYPE_CODE                      = DP.BOOK_TYPE_CODE
AND CP.CALENDAR_TYPE                       = BC.DEPRN_CALENDAR
AND TH.TRANSACTION_DATE_ENTERED BETWEEN CP.START_DATE AND CP.END_DATE
AND (TH.DATE_EFFECTIVE BETWEEN DP.PERIOD_OPEN_DATE AND NVL(DP.PERIOD_CLOSE_DATE,SYSDATE)
AND DP.BOOK_TYPE_CODE        = TH.BOOK_TYPE_CODE)
AND AD.ASSET_ID              = BK.ASSET_ID
AND TH.TRANSACTION_HEADER_ID = BK.TRANSACTION_HEADER_ID_IN
/


select * From all_objects where object_name = 'FA_BOOKS_BAS';
select * From all_synonyms where synonym_name = 'FA_BOOKS_BAS';  -- Point to FA Book as well!!

