SELECT * FROM all_views WHERE view_name = 'FA_INVOICE_DETAILS_V';
SELECT AI.ROWID ROW_ID ,
  AI.ASSET_ID ,
  AI.PO_VENDOR_ID ,
  AI.ASSET_INVOICE_ID ,
  AI.FIXED_ASSETS_COST ,
  AI.DATE_EFFECTIVE ,
  AI.DATE_INEFFECTIVE ,
  AI.INVOICE_TRANSACTION_ID_IN ,
  AI.INVOICE_TRANSACTION_ID_OUT ,
  AI.DELETED_FLAG ,
  AI.PO_NUMBER ,
  AI.INVOICE_NUMBER ,
  AI.PAYABLES_BATCH_NAME ,
  AI.PAYABLES_CODE_COMBINATION_ID ,
  AI.FEEDER_SYSTEM_NAME ,
  AI.CREATE_BATCH_DATE ,
  AI.CREATE_BATCH_ID ,
  AI.INVOICE_DATE ,
  AI.PAYABLES_COST ,
  AI.POST_BATCH_ID ,
  AI.INVOICE_ID ,
  AI.AP_DISTRIBUTION_LINE_NUMBER ,
  AI.PAYABLES_UNITS ,
  AI.SPLIT_MERGED_CODE ,
  AI.DESCRIPTION ,
  AI.PARENT_MASS_ADDITION_ID ,
  AI.LAST_UPDATE_DATE ,
  AI.LAST_UPDATED_BY ,
  AI.LAST_UPDATE_LOGIN ,
  AI.CREATED_BY ,
  AI.CREATION_DATE ,
  AI.ATTRIBUTE1 ,
  AI.ATTRIBUTE2 ,
  AI.ATTRIBUTE3 ,
  AI.ATTRIBUTE4 ,
  AI.ATTRIBUTE5 ,
  AI.ATTRIBUTE6 ,
  AI.ATTRIBUTE7 ,
  AI.ATTRIBUTE8 ,
  AI.ATTRIBUTE9 ,
  AI.ATTRIBUTE10 ,
  AI.ATTRIBUTE11 ,
  AI.ATTRIBUTE12 ,
  AI.ATTRIBUTE13 ,
  AI.ATTRIBUTE14 ,
  AI.ATTRIBUTE15 ,
  AI.ATTRIBUTE_CATEGORY_CODE ,
  AI.UNREVALUED_COST ,
  AI.MERGED_CODE ,
  AI.SPLIT_CODE ,
  AI.MERGE_PARENT_MASS_ADDITIONS_ID ,
  AI.SPLIT_PARENT_MASS_ADDITIONS_ID ,
  AI.PROJECT_ASSET_LINE_ID ,
  AI.PROJECT_ID ,
  AI.TASK_ID ,
  PO.SEGMENT1 VENDOR_NUMBER ,
  PO.VENDOR_NAME ,
  AI.SOURCE_LINE_ID ,
  AI.DEPRECIATE_IN_GROUP_FLAG ,
  AI.MATERIAL_INDICATOR_FLAG,
  AI.PRIOR_SOURCE_LINE_ID,
  AI.INVOICE_DISTRIBUTION_ID,
  AI.INVOICE_LINE_NUMBER,
  AI.PO_DISTRIBUTION_ID
FROM PO_VENDORS PO ,
  FA_ASSET_INVOICES AI
WHERE AI.DATE_INEFFECTIVE IS NULL
AND PO.VENDOR_ID(+)        = AI.PO_VENDOR_ID
/

SELECT * FROM all_views WHERE view_name = 'PO_VENDORS';

SELECT
   PAV.VENDOR_ID	 		VENDOR_ID
   ,PAV.LAST_UPDATE_DATE	 		LAST_UPDATE_DATE
   ,PAV.LAST_UPDATED_BY	 		LAST_UPDATED_BY
   ,PAV.VENDOR_NAME	 			VENDOR_NAME
   ,HP.ORGANIZATION_NAME_PHONETIC	 	VENDOR_NAME_ALT
   ,PAV.SEGMENT1	 			SEGMENT1
   ,PAV.SUMMARY_FLAG	 		SUMMARY_FLAG
   ,PAV.ENABLED_FLAG	 		ENABLED_FLAG
   ,PAV.SEGMENT2	 			SEGMENT2
   ,PAV.SEGMENT3	 			SEGMENT3
   ,PAV.SEGMENT4	 			SEGMENT4
   ,PAV.SEGMENT5	 			SEGMENT5
   ,PAV.LAST_UPDATE_LOGIN	 		LAST_UPDATE_LOGIN
   ,PAV.CREATION_DATE	 		CREATION_DATE
   ,PAV.CREATED_BY	 			CREATED_BY
   ,PAV.EMPLOYEE_ID	 			EMPLOYEE_ID
   ,PAV.VENDOR_TYPE_LOOKUP_CODE	 	VENDOR_TYPE_LOOKUP_CODE
   ,PAV.CUSTOMER_NUM	 		CUSTOMER_NUM
   ,PAV.ONE_TIME_FLAG	 		ONE_TIME_FLAG
   ,PAV.PARENT_VENDOR_ID 	 		PARENT_VENDOR_ID
   ,PAV.MIN_ORDER_AMOUNT	 		MIN_ORDER_AMOUNT
   ,PAV.TERMS_ID	 			TERMS_ID
   ,PAV.SET_OF_BOOKS_ID	 		SET_OF_BOOKS_ID
   ,PAV.ALWAYS_TAKE_DISC_FLAG	 	ALWAYS_TAKE_DISC_FLAG
   ,PAV.PAY_DATE_BASIS_LOOKUP_CODE	 	PAY_DATE_BASIS_LOOKUP_CODE
   ,PAV.PAY_GROUP_LOOKUP_CODE	 	PAY_GROUP_LOOKUP_CODE
   ,PAV.PAYMENT_PRIORITY	 		PAYMENT_PRIORITY
   ,PAV.INVOICE_CURRENCY_CODE	 	INVOICE_CURRENCY_CODE
   ,PAV.PAYMENT_CURRENCY_CODE	 	PAYMENT_CURRENCY_CODE
   ,PAV.INVOICE_AMOUNT_LIMIT	 	INVOICE_AMOUNT_LIMIT
   ,PAV.HOLD_ALL_PAYMENTS_FLAG	 	HOLD_ALL_PAYMENTS_FLAG
   ,PAV.HOLD_FUTURE_PAYMENTS_FLAG	 	HOLD_FUTURE_PAYMENTS_FLAG
   ,PAV.HOLD_REASON	 			HOLD_REASON
   ,HP.JGZZ_FISCAL_CODE	 		NUM_1099
   ,PAV.INDIVIDUAL_1099			INDIVIDUAL_1099
   ,PAV.TYPE_1099	 			TYPE_1099
   ,PAV.WITHHOLDING_STATUS_LOOKUP_CODE	WITHHOLDING_STATUS_LOOKUP_CODE
   ,PAV.WITHHOLDING_START_DATE	 	WITHHOLDING_START_DATE
   ,PAV.ORGANIZATION_TYPE_LOOKUP_CODE	ORGANIZATION_TYPE_LOOKUP_CODE
   ,PAV.START_DATE_ACTIVE	 		START_DATE_ACTIVE
   ,PAV.END_DATE_ACTIVE	 		END_DATE_ACTIVE
   ,PAV.MINORITY_GROUP_LOOKUP_CODE	 	MINORITY_GROUP_LOOKUP_CODE
   ,PAV.WOMEN_OWNED_FLAG	 		WOMEN_OWNED_FLAG
   ,PAV.SMALL_BUSINESS_FLAG	 		SMALL_BUSINESS_FLAG
   ,PAV.STANDARD_INDUSTRY_CLASS                  STANDARD_INDUSTRY_CLASS
   ,PAV.HOLD_FLAG	 			HOLD_FLAG
   ,PAV.PURCHASING_HOLD_REASON		PURCHASING_HOLD_REASON
   ,PAV.HOLD_BY	 			HOLD_BY
   ,PAV.HOLD_DATE	 			HOLD_DATE
   ,PAV.TERMS_DATE_BASIS	 		TERMS_DATE_BASIS
   ,PAV.INSPECTION_REQUIRED_FLAG	 	INSPECTION_REQUIRED_FLAG
   ,PAV.RECEIPT_REQUIRED_FLAG	 	RECEIPT_REQUIRED_FLAG
   ,PAV.QTY_RCV_TOLERANCE	 		QTY_RCV_TOLERANCE
   ,PAV.QTY_RCV_EXCEPTION_CODE	 	QTY_RCV_EXCEPTION_CODE
   ,PAV.ENFORCE_SHIP_TO_LOCATION_CODE	ENFORCE_SHIP_TO_LOCATION_CODE
   ,PAV.DAYS_EARLY_RECEIPT_ALLOWED	 	DAYS_EARLY_RECEIPT_ALLOWED
   ,PAV.DAYS_LATE_RECEIPT_ALLOWED	 	DAYS_LATE_RECEIPT_ALLOWED
   ,PAV.RECEIPT_DAYS_EXCEPTION_CODE	 	RECEIPT_DAYS_EXCEPTION_CODE
   ,PAV.RECEIVING_ROUTING_ID	 	RECEIVING_ROUTING_ID
   ,PAV.ALLOW_SUBSTITUTE_RECEIPTS_FLAG	ALLOW_SUBSTITUTE_RECEIPTS_FLAG
   ,PAV.ALLOW_UNORDERED_RECEIPTS_FLAG	ALLOW_UNORDERED_RECEIPTS_FLAG
   ,PAV.HOLD_UNMATCHED_INVOICES_FLAG	HOLD_UNMATCHED_INVOICES_FLAG
   ,PAV.TAX_VERIFICATION_DATE	 	TAX_VERIFICATION_DATE
   ,PAV.NAME_CONTROL	 		NAME_CONTROL
   ,PAV.STATE_REPORTABLE_FLAG		STATE_REPORTABLE_FLAG
   ,PAV.FEDERAL_REPORTABLE_FLAG		FEDERAL_REPORTABLE_FLAG
   ,PAV.ATTRIBUTE_CATEGORY	 		ATTRIBUTE_CATEGORY
   ,PAV.ATTRIBUTE1	 			ATTRIBUTE1
   ,PAV.ATTRIBUTE2	 			ATTRIBUTE2
   ,PAV.ATTRIBUTE3	 			ATTRIBUTE3
   ,PAV.ATTRIBUTE4	 			ATTRIBUTE4
   ,PAV.ATTRIBUTE5	 			ATTRIBUTE5
   ,PAV.ATTRIBUTE6	 			ATTRIBUTE6
   ,PAV.ATTRIBUTE7	 			ATTRIBUTE7
   ,PAV.ATTRIBUTE8	 			ATTRIBUTE8
   ,PAV.ATTRIBUTE9	 			ATTRIBUTE9
   ,PAV.ATTRIBUTE10	 			ATTRIBUTE10
   ,PAV.ATTRIBUTE11	 			ATTRIBUTE11
   ,PAV.ATTRIBUTE12	 			ATTRIBUTE12
   ,PAV.ATTRIBUTE13	 			ATTRIBUTE13
   ,PAV.ATTRIBUTE14	 			ATTRIBUTE14
   ,PAV.ATTRIBUTE15	 			ATTRIBUTE15
   ,PAV.REQUEST_ID	 			REQUEST_ID
   ,PAV.PROGRAM_APPLICATION_ID		PROGRAM_APPLICATION_ID
   ,PAV.PROGRAM_ID	 			PROGRAM_ID
   ,PAV.PROGRAM_UPDATE_DATE	 		PROGRAM_UPDATE_DATE
   ,substr(HP.TAX_REFERENCE,1,20) 		VAT_REGISTRATION_NUM
   ,PAV.AUTO_CALCULATE_INTEREST_FLAG 	AUTO_CALCULATE_INTEREST_FLAG
   ,PAV.VALIDATION_NUMBER	 		VALIDATION_NUMBER
   ,PAV.EXCLUDE_FREIGHT_FROM_DISCOUNT 	EXCLUDE_FREIGHT_FROM_DISCOUNT
   ,PAV.TAX_REPORTING_NAME	 		TAX_REPORTING_NAME
   ,PAV.CHECK_DIGITS	 		CHECK_DIGITS
   ,PAV.ALLOW_AWT_FLAG	 		ALLOW_AWT_FLAG
   ,PAV.AWT_GROUP_ID	 		AWT_GROUP_ID
   ,PAV.GLOBAL_ATTRIBUTE1	 		GLOBAL_ATTRIBUTE1
   ,PAV.GLOBAL_ATTRIBUTE2	 		GLOBAL_ATTRIBUTE2
   ,PAV.GLOBAL_ATTRIBUTE3	 		GLOBAL_ATTRIBUTE3
   ,PAV.GLOBAL_ATTRIBUTE4	 		GLOBAL_ATTRIBUTE4
   ,PAV.GLOBAL_ATTRIBUTE5	 		GLOBAL_ATTRIBUTE5
   ,PAV.GLOBAL_ATTRIBUTE6	 		GLOBAL_ATTRIBUTE6
   ,PAV.GLOBAL_ATTRIBUTE7	 		GLOBAL_ATTRIBUTE7
   ,PAV.GLOBAL_ATTRIBUTE8	 		GLOBAL_ATTRIBUTE8
   ,PAV.GLOBAL_ATTRIBUTE9	 		GLOBAL_ATTRIBUTE9
   ,PAV.GLOBAL_ATTRIBUTE10	 		GLOBAL_ATTRIBUTE10
   ,PAV.GLOBAL_ATTRIBUTE11	 		GLOBAL_ATTRIBUTE11
   ,PAV.GLOBAL_ATTRIBUTE12	 		GLOBAL_ATTRIBUTE12
   ,PAV.GLOBAL_ATTRIBUTE13	 		GLOBAL_ATTRIBUTE13
   ,PAV.GLOBAL_ATTRIBUTE14	 		GLOBAL_ATTRIBUTE14
   ,PAV.GLOBAL_ATTRIBUTE15	 		GLOBAL_ATTRIBUTE15
   ,PAV.GLOBAL_ATTRIBUTE16	 		GLOBAL_ATTRIBUTE16
   ,PAV.GLOBAL_ATTRIBUTE17	 		GLOBAL_ATTRIBUTE17
   ,PAV.GLOBAL_ATTRIBUTE18	 		GLOBAL_ATTRIBUTE18
   ,PAV.GLOBAL_ATTRIBUTE19	 		GLOBAL_ATTRIBUTE19
   ,PAV.GLOBAL_ATTRIBUTE20	 		GLOBAL_ATTRIBUTE20
   ,PAV.GLOBAL_ATTRIBUTE_CATEGORY		GLOBAL_ATTRIBUTE_CATEGORY
   ,PAV.BANK_CHARGE_BEARER	 		BANK_CHARGE_BEARER
   ,PAV.MATCH_OPTION	 		MATCH_OPTION
   ,PAV.CREATE_DEBIT_MEMO_FLAG		CREATE_DEBIT_MEMO_FLAG
   ,PAV.PARTY_ID				PARTY_ID
   ,PAV.PARENT_PARTY_ID				PARENT_PARTY_ID
   ,PAV.NI_NUMBER                               NI_NUMBER
   ,HP.PARTY_NUMBER                             PARTY_NUMBER
   ,PAV.PAY_AWT_GROUP_ID                        PAY_AWT_GROUP_ID  
FROM
   AP_SUPPLIERS PAV,
   HZ_PARTIES HP
WHERE
   PAV.PARTY_ID = HP.PARTY_ID
/
