SELECT TRANSACTION_HEADER_ID_IN,
  TRANSACTION_TYPE,
  TRANSACTION_DATE_ENTERED,
  PERIOD_EFFECTIVE,
  PERIOD_ENTERED,
  FISCAL_YEAR,
  CURRENT_COST,
  BOOK_TYPE_CODE,
  ASSET_ID,
  ASSET_NUMBER
FROM FA_FINANCIAL_INQUIRY_COST_V
WHERE (BOOK_TYPE_CODE='OPS CORP')
AND (ASSET_ID        =100076)
ORDER BY transaction_header_id_in DESC