SELECT ASSET_NUMBER,
  DESCRIPTION,
  TAG_NUMBER,
  SERIAL_NUMBER,
  ASSET_TYPE,
  CURRENT_UNITS,
  PARENT_ASSET,
  PARENT_DESCRIPTION,
  ATTRIBUTE15,
  MANUFACTURER_NAME,
  MODEL_NUMBER,
  LEASE_NUMBER,
  LESSOR,
  LEASE_DESC,
  PROPERTY_TYPE_CODE,
  PROPERTY_TYPE_MEANING,
  OWNED_LEASED,
  PROPERTY_1245_1250_CODE,
  PROPERTY_1245_1250_MEANING,
  NEW_USED,
  IN_USE_FLAG,
  INVENTORIAL,
  ROW_ID,
  ASSET_ID,
  ASSET_KEY_CCID,
  ASSET_CATEGORY_ID,
  PARENT_ASSET_ID,
  LEASE_ID,
  UNIT_ADJUSTMENT_FLAG,
  ADD_COST_JE_FLAG,
  CATEGORY_TYPE,
  ATTRIBUTE1,  ATTRIBUTE2,  ATTRIBUTE3,  ATTRIBUTE4,  ATTRIBUTE5,
  ATTRIBUTE6,  ATTRIBUTE7,  ATTRIBUTE8,  ATTRIBUTE9,  ATTRIBUTE10,
  ATTRIBUTE11,  ATTRIBUTE12,  ATTRIBUTE13,  ATTRIBUTE14,  ATTRIBUTE15
  ATTRIBUTE16,  ATTRIBUTE17,  ATTRIBUTE18,  ATTRIBUTE19,  ATTRIBUTE20,
  ATTRIBUTE21,  ATTRIBUTE22,  ATTRIBUTE23,  ATTRIBUTE24,  ATTRIBUTE25,
  ATTRIBUTE26,  ATTRIBUTE27,  ATTRIBUTE28,  ATTRIBUTE29,  ATTRIBUTE30,
  CONTEXT,
  LS_ATTRIBUTE1,
  LS_ATTRIBUTE2,
  LS_ATTRIBUTE3,
  LS_ATTRIBUTE4,
  LS_ATTRIBUTE5,
  LS_ATTRIBUTE6,
  LS_ATTRIBUTE7,
  LS_ATTRIBUTE8,
  LS_ATTRIBUTE9,
  LS_ATTRIBUTE10,
  LS_ATTRIBUTE11,
  LS_ATTRIBUTE12,
  LS_ATTRIBUTE13,
  LS_ATTRIBUTE14,
  LS_ATTRIBUTE15,
  LS_ATTRIBUTE_CATEGORY_CODE
FROM FA_ADDITIONS_V
WHERE ((''     IS NULL)
OR (''          = 'N'
AND asset_type <> 'GROUP'))
AND             -1          =-1
AND (ASSET_ID  IN
  (SELECT ASSET_ID
  FROM FA_BOOKS fb,
    FA_BOOK_CONTROLS_SEC sec
  WHERE fb.BOOK_TYPE_CODE        = 'VISION LEASE'
  AND NVL(DISABLED_FLAG, 'N')    = 'N'
  AND transaction_header_id_out IS NULL
  AND fb.BOOK_TYPE_CODE          = sec.BOOK_TYPE_CODE
  ))
ORDER BY asset_number