SELECT CURRENT_COST,
  ORIGINAL_COST,
  SALVAGE_VALUE,
  ADJUSTED_RECOVERABLE_COST,
  REVALUATION_CEILING,
  DEPRN_METHOD_CODE,
  LIFE,
  ADJUSTED_RATE,
  PRODUCTION_CAPACITY,
  UNIT_OF_MEASURE,
  PRORATE_CONVENTION_CODE,
  PRORATE_DATE,
  DATE_PLACED_IN_SERVICE,
  DEPRECIATE_FLAG,
  BONUS_RULE,
  CEILING_NAME,
  ASSET_NUMBER,
  TRANSACTION_HEADER_ID_IN,
  TRANSACTION_HEADER_ID_OUT,
  KEY, --Reference Number
  ASSET_ID,
  GROUP_ASSET_NUMBER
FROM FA_TRANSACTION_HISTORY_BOOKS_V
WHERE (KEY=110)
ORDER BY TRANSACTION_HEADER_ID_IN
/
SELECT CURRENT_COST,
  ORIGINAL_COST,
  SALVAGE_VALUE,
  ADJUSTED_RECOVERABLE_COST,
  REVALUATION_CEILING,
  DEPRN_METHOD_CODE,
  LIFE,
  ADJUSTED_RATE,
  PRODUCTION_CAPACITY,
  UNIT_OF_MEASURE,
  PRORATE_CONVENTION_CODE,
  PRORATE_DATE,
  DATE_PLACED_IN_SERVICE,
  DEPRECIATE_FLAG,
  BONUS_RULE,
  CEILING_NAME,
  ASSET_NUMBER,
  TRANSACTION_HEADER_ID_IN,
  TRANSACTION_HEADER_ID_OUT,
  KEY,
  ASSET_ID,
  GROUP_ASSET_NUMBER
FROM FA_TRANSACTION_HISTORY_BOOKS_V
WHERE (KEY=110)
ORDER BY TRANSACTION_HEADER_ID_IN